### ISSUE TITLE
python craft serve   watchdog error on windows 10

### ISSUE THREAD

**Issue by tanero** [MasoniteFramework/masonite#777]
### Describe the bug

On windows 10,  pip installs masonite packages successfully.  But when I try to start development server by python craft serve  gives below error message.  After upgrading the watchdog package to 3.0.0 fixed the error.

> ImportError

  cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events'

### Expected behaviour

> WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8000
Press CTRL+C to quit
 * Restarting with watchdog (windowsapi)

### Steps to reproduce the bug

1. pip install masonite
2. project start myproject
3. cd myproject
4. project install
5. python craft serve

### Screenshots

**Error Message:** 

![image](https://github.com/MasoniteFramework/masonite/assets/3600684/62ca2d2d-94bd-4e21-b6cf-fe34fc1788e0)

**Upgrade watchdog:**

![image](https://github.com/MasoniteFramework/masonite/assets/3600684/7dee8b16-7256-4a40-90d4-39483288c778)

**After upgrade watchdog:**

![image](https://github.com/MasoniteFramework/masonite/assets/3600684/19ef57c2-e2fc-4776-841c-312afcf7ef5a)

### OS

Windows

### OS version

10

### Masonite Version

4.18.0
